export const caseStudyLayout = {
  heroSection: "relative border-b border-softWhite/10 bg-deepIndigo pb-14 pt-16 md:pb-20 md:pt-20",
  heroContainer: "site-container relative",
  backLink: "mb-10 inline-flex items-center gap-2 rounded-full border border-softWhite/16 bg-archiveBlue/36 px-3 py-2 text-sm font-bold text-acidGreen transition hover:border-acidGreen",
  heroComposition: "relative",
  heroCopy: "max-w-6xl",
  category: "font-mono text-sm font-bold uppercase tracking-[0.12em] text-acidGreen/88",
  heroTitle: "mt-5 whitespace-pre-line font-display text-[clamp(3rem,8vw,7.9rem)] leading-[1.12] text-softWhite",
  heroTitleEditor: "block w-full resize-none overflow-hidden rounded-[6px] border border-softWhite/10 bg-deepIndigo/58 px-3 py-3 font-display text-[clamp(3rem,8vw,7.9rem)] leading-[1.12] text-softWhite outline-none transition placeholder:text-softWhite/28 focus:border-acidGreen/60",
  subtitle: "mt-6 max-w-3xl text-[clamp(1.125rem,1.5vw,1.5rem)] leading-[1.65] text-softWhite/70",
  durationPosition: "mt-3 sm:absolute sm:right-0 sm:top-0 sm:mt-0",
  durationText: "font-mono text-sm font-medium leading-5 text-[#9FAAD2] sm:text-right",
  contentSection: "bg-deepIndigo py-16 md:py-24",
  contentStack: "site-container grid gap-24 md:gap-32",
  majorGrid: "grid min-w-0 items-start gap-8 xl:grid-cols-[minmax(290px,0.78fr)_minmax(0,1.62fr)] xl:gap-x-[clamp(4rem,6vw,6rem)]",
  majorTitleComposition: "relative isolate min-h-[clamp(10rem,18vw,16rem)] min-w-0 self-start overflow-hidden pb-6 xl:-translate-y-[0.875rem]",
  majorNumber: "pointer-events-none absolute left-0 top-0 z-0 font-display text-[clamp(7rem,14vw,16rem)] leading-none text-[#2B3268]/45",
  majorTitleOffset: "relative z-10 ml-[clamp(1.5rem,3.5vw,4.5rem)] min-w-0 pt-[clamp(0.5rem,0.9vw,1rem)]",
  majorTitle: "break-words font-display text-[clamp(3.6rem,6vw,7rem)] leading-[1.12] text-acidGreen",
  majorCopy: "min-w-0 max-w-[52rem] self-start",
  majorHeading: "font-display text-[clamp(1.5rem,2.4vw,2.75rem)] leading-[1.3] text-softWhite/78",
  majorBody: "mt-8 text-[clamp(1.05rem,1.15vw,1.25rem)] leading-[1.75] text-softWhite/70",
  blocks: "mt-14 grid min-w-0 gap-12",
} as const;
